# Generated by Django 5.1.5 on 2025-01-31 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
